version: "3.8"
services:
   app:
      container_name: my-personal-library-app
      build: .
      ports:
         - "3002:3000"
      depends_on:
         - db
      environment:
         - DB_HOST=db
         - DB_USER=${DB_USER}
         - DB_PASSWORD=${DB_PASSWORD}
         - DB_DATABASE=${DB_DATABASE}
      volumes:
         - ./uploads:/usr/src/app/uploads

   db:
      container_name: my-personal-library-db
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      environment:
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
         - MYSQL_DATABASE=${DB_DATABASE}
      ports:
         - "3306:3306"
      volumes:
         - db-data:/var/lib/mysql

   phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: my-personal-library-phpmyadmin
      environment:
         - PMA_HOST=db
         - PMA_USER=${DB_USER}
         - PMA_PASSWORD=${DB_PASSWORD}
      ports:
         - "8082:80"
      depends_on:
         - db

   frontend:
      container_name: my-personal-library-frontend
      build:
         context: ../my-personal-librarypro
         dockerfile: Dockerfile
      ports:
         - "4200:80"
      volumes:
         - ../my-personal-librarypro/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
   db-data: # This volume doesn't need any specific configuration here
